export { default as About } from "./About/About"
export { default as Blog } from "./Blog/Blog"
export { default as Featured } from "./Featured/Featured"
export { default as Header } from "./Header/Header"
export { default as Latest } from "./Latest/Latest"